api_gateway_sql:
  timeout: 10s
  auth:
    enabled: true
    username: test
    password: test@test
  databases:
  - name: datasource
    type: sqlite
    host: 127.0.0.1
    port: 3306
    username: "test"
    password: "test"
    dbname: test
    sslmode: false
  targets:
  - name: list-student
    data_source_name: datasource1
    datafields: ""
    multi: false
    sql: "select * from student"