api_gateway_sql:
  timeout: 10s
  auth:
    enabled: true
    username: test
    password: test@test
  databases:
  - name: datasource1
    type: mariadb
    host: 127.0.0.1
    port: 3306
    username: "test"
    password: "test"
    dbname: test
    sslmode: false
  - name: datasource2
    type: mysql
    host: 127.0.0.1
    port: 3306
    username: "test"
    password: "test"
    dbname: test
    sslmode: false
  - name: datasource3
    type: postgres
    host: 127.0.0.1
    port: 3306
    username: "test"
    password: "test"
    dbname: test
    sslmode: false
  targets:
  - name: list-student
    data_source_name: datasource1
    datafields: ""
    sql: "select * from student"